### ISSUE TITLE
Add bot to more channels

### ISSUE THREAD

**Issue by gustafe** [tmolnar0831/photter#15]
It would be ideal if the same bot could be in different channels.

Channels can require a password, this should be handled.

**Comment by tmolnar0831** [comment]
Let's separate the two things: adding the bot to multiple channels is one task, the channel password is another.

**Comment by tmolnar0831** [comment]
This commit will solve the multi-channel join:

f2f6455b42cd41726aa4c7c56761c484cb2e12f2

**Comment by tmolnar0831** [comment]
It is ready and tested. Could you please open a new one for the password protected channels? That is a separate issue.
