### ISSUE TITLE
Alternative API?

### ISSUE THREAD

**Issue by gustafe** [tmolnar0831/photter#16]
I've heard that APIXU exists but is not ideal.

https://www.apixu.com/

Another alternative is wunderground

https://www.wunderground.com/

**Comment by tmolnar0831** [comment]
Wunderground has just shut down its free API. Apixu seems a bit hardcore, I will take a look at it.

**Comment by tmolnar0831** [comment]
https://www.apixu.com/doc/current.aspx

**Comment by tmolnar0831** [comment]
#19 has been merged to master.

**Comment by tmolnar0831** [comment]
Let's consider it ready. The Wiki has been updated too. New dependency: cl-apixu!
