### ISSUE TITLE
Error message causes flood protection to trigger, kicking the bot

### ISSUE THREAD

**Issue by gustafe** [tmolnar0831/photter#24]
Trying to query an unknown location gives the following error

==>    13:17 < Coraxyn> Thanks Gustaf 
    13:17 < gustaf> .weather Isle of Man
    13:17 <+pg-bot> Sorry, I got an error: The value of VECTOR is "<!DOCTYPE html>
              Quits: pg-bot

Message in REPL:

==> UNHANDLED-EVENT:3757580221: PRIVMSG: Coraxyn #photogeeks "Thanks Gustaf" 
UNHANDLED-EVENT:3757580224: ERR_UNKNOWNCOMMAND: cherryh.freenode.net pg-bot <html> "Unknown command"
UNHANDLED-EVENT:3757580224: ERR_UNKNOWNCOMMAND: cherryh.freenode.net pg-bot <head> "Unknown command"
UNHANDLED-EVENT:3757580224: ERR_UNKNOWNCOMMAND: cherryh.freenode.net pg-bot <title>Runtime "Unknown command"
UNHANDLED-EVENT:3757580224: ERR_UNKNOWNCOMMAND: cherryh.freenode.net pg-bot <meta "Unknown command"
UNHANDLED-EVENT:3757580224: ERROR:  "Closing Link: 165.227.165.91 (Excess Flood)"

**Comment by tmolnar0831** [comment]
<st_iron> .weather isle of man
<photter-dev> Sulby, Isle of Man, Partly cloudy, 4.3°C, feels like -2.3°C,
              wind 50.8kph NW, precipitation 0.0mm, humidity 62%, UV 2.0

**Comment by tmolnar0831** [comment]
I tried a series of problematic commands in the test room with OQ, but we cannot reproduce the issue.

**Comment by gustafe** [comment]
Output should still be limited to 3 or 4 lines (even errors) to prevent a denial of service attack on the bot.

**Comment by tmolnar0831** [comment]
It seems that the main issue is the "newline" character in the response from HTTP. It must be stripped first, because the IRCd treats it as a command evaluation. The bot can split the long output to chunks of messages.

**Comment by gustafe** [comment]
Another example... 

[error.txt](https://github.com/tmolnar0831/photter/files/2802799/error.txt)

**Comment by tmolnar0831** [comment]
#25 fixes it.

**Comment by tmolnar0831** [comment]
I close it now, it can be reopened if necessary.
