### ISSUE TITLE
Link echoing chokes, reporting UTF error

### ISSUE THREAD

**Issue by gustafe** [tmolnar0831/photter#30]
test link: 

https://www.amazon.com/dp/B00K5MIVN6/

15:15 < gustaf> testing https://www.amazon.com/dp/B00K5MIVN6/
15:15 < pg-bot> Sorry, I got an error: Unexpected value #x8B at start of UTF-8
                sequence.
15:15 < photter> Sorry, I got an error: Unexpected value #x8B at start of UTF-8
                 sequence.

15:17 < gustaf> .version
15:17 < pg-bot> Version: 2.0.5
15:17 < photter> Version: 2.1.0

**Comment by tmolnar0831** [comment]
This is an issue at the vendor site.
They set the communication to UTF-8 stritct, then they're sending Latin-1 characters.

**Comment by tmolnar0831** [comment]
So Amazon just fixed it. :)
