### ISSUE TITLE
Blanks

### ISSUE THREAD

**Issue by coraxyn** [tmolnar0831/photter#35]
In URL echo Imgur (and perhaps others) have leading blanks.  Suggest trimming leading and trailing blanks in response

**Comment by tmolnar0831** [comment]
https://lispcookbook.github.io/cl-cookbook/strings.html#trimming-blanks-from-the-ends-of-a-string

**Comment by tmolnar0831** [comment]
Fix: https://github.com/tmolnar0831/photter/pull/37
